apiVersion: v1
kind: Service
metadata:
  name: kubernetes-example-service
  labels:
    name: kubernetes-example-app
spec:
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
  selector:
    app: kubernetes-example-app
  type: LoadBalancer